name: Docker Image CI/CD 2048

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Проверка версии Node.js и npm
        run: |
          node -v
          npm -v

      - name: Установка semver
        run: |
          npm install -g semver

      - name: Проверка версии semver
        run: semver --version

      - name: Получение новой версии
        id: version
        run: |
          set -e
          echo "VERSION=$(semver bump patch)" >> $GITHUB_ENV

      - name: Проверка версии
        run: echo "Текущая версия: $VERSION"

      - name: Вход в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и публикация Docker образа
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-site2048:latest
            ${{ secrets.DOCKER_USERNAME }}/my-site2048:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/my-site2048:${{ env.VERSION }}

      - name: Подключение к серверу и обновление Docker Compose
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker-compose pull && docker-compose up -d
